[package]
name = "roots"
version = "0.1.0"
authors = ["Michael George <mdgeorge@cs.cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alga = "0.9.3"
alga_derive = "0.9"
